Eric Capponi customer entity
newrelic/entity-definitions pull request #1190
Opened 2023-08-21 20:25 UTC by EricCapponi

### Relevant information

### Checklist

* [ X] I've read the guidelines and understand the acceptance criteria.
* [ X] The value of the attribute marked as `identifier` will be unique and valid. 
* [ X] I've confirmed that my entity type wasn't already defined. If it is I'm providing an explanation above.

2023-08-21 20:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/entity-definitions?pullRequest=1190) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/entity-definitions?pullRequest=1190) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/entity-definitions?pullRequest=1190) it.</sub>

2023-09-12 08:12 UTC, apoloa requested changes
Can you change the folder name from: 
```
entity-types/ext-customer/*.yml
```
to 
```
entity-types/ext-customer_consumption/*.yml
```

2023-09-12 08:12 UTC, apoloa commented on entity-types/ext-customer/definition.yml
> +# dashboardTemplates:
Can you delete this comment?

2023-09-12 08:43 UTC, lujop approved these changes
Appart from apoloa comments it LGTM

2023-09-18 13:39 UTC, andre-nr commented
closed, as discussed on the help channel

2023-09-19 13:57 UTC, closed without merging