Convert Varnish Instance dashboard back to sample
newrelic/entity-definitions pull request #1338
Opened 2023-12-18 11:03 UTC by jlegoff

### Relevant information

Convert Varnish Instance dashboard back to sample

### Checklist

* [ ] I've read the guidelines and understand the acceptance criteria.
* [ ] The value of the attribute marked as `identifier` will be unique and valid. 
* [ ] I've confirmed that my entity type wasn't already defined. If it is I'm providing an explanation above.

2023-12-18 11:03 UTC, naxhh requested changes
beep boop bop.

I have found some errors processing these changes:

 ```
* Error VALIDATING domainType: 'INFRA-RABBITMQQUEUE' on Golden metrics for key 'SELECT average(rabbitmq.message.delivered) FROM Metric WHERE entity.guid IN ('guid') FACET entity.name TIMESERIES' - Exception: The select clause uses a different value function than the rest.

* Error VALIDATING domainType: 'INFRA-RABBITMQQUEUE' on Golden metrics for key 'SELECT average(rabbitmq.message.published) FROM Metric WHERE entity.guid IN ('guid') FACET entity.name TIMESERIES' - Exception: The select clause uses a different value function than the rest.
```

2023-12-18 11:03 UTC, naxhh requested changes
beep boop bop.

I have found some errors processing these changes:

 ```
* Error VALIDATING domainType: 'INFRA-RABBITMQQUEUE' on Golden metrics for key 'SELECT average(rabbitmq.message.delivered) FROM Metric WHERE entity.guid IN ('guid') FACET entity.name TIMESERIES' - Exception: The select clause uses a different value function than the rest.

* Error VALIDATING domainType: 'INFRA-RABBITMQQUEUE' on Golden metrics for key 'SELECT average(rabbitmq.message.published) FROM Metric WHERE entity.guid IN ('guid') FACET entity.name TIMESERIES' - Exception: The select clause uses a different value function than the rest.
```

2024-01-09 12:18 UTC, naxhh approved these changes

2024-01-09 12:18 UTC, lujop approved these changes

2024-01-10 10:50 UTC, naxhh approved these changes

2024-01-10 10:50 UTC, naxhh approved these changes

2024-01-10 10:51 UTC, merged