APM/OTel Relationship with AWS MQ Topic
newrelic/entity-definitions pull request #1637
Opened 2024-05-22 12:19 UTC by Sanjalee-NewRelic

### Relevant information

For any service instrumented using Otel or New Relic APM, a service map is shown in the new relic dashboard which displays the relationship between the service in question and other entities it is dependent on.

In case a service calls a MQ service of AWS, this relationship is not shown in the service map. Instead, it shows that the service calls an external entity.

With the code changes in this PR, the user can correctly see the relationship between the Otel/APM service and Amazon MQ Topic (ActiveMQ or RabbitMQ)

### Checklist

* [ ] I've read the guidelines and understand the acceptance criteria.
* [ ] The value of the attribute marked as `identifier` will be unique and valid. 
* [ ] I've confirmed that my entity type wasn't already defined. If it is I'm providing an explanation above.

2024-06-19 11:14 UTC, javimb requested changes

2024-06-19 11:14 UTC, javimb commented on relationships/synthesis/APM-APPLICATION-to-INFRA-AWSMQTOPIC.yml
> +        regex: "MessageBroker/[^/]*/Topic/Produce/Named/[^/]*\\.mq\\.[^/]*\\.amazonaws\\.com/[0-9]+"
Can you share a link to data matching this expression?

2024-06-19 11:14 UTC, javimb commented on relationships/synthesis/EXT-SERVICE-to-INFRA-AWSMQTOPIC.yml
> +    conditions:
These conditions are too open. You need to introduce something more specific to AWS MQ (or ActiveMQ).

2024-06-19 11:14 UTC, javimb commented on relationships/candidates/AWSMQTOPIC.yml
> +category: AWSMQTOPIC
Shouldn't we generalize this to ActiveMQ, as we did for ElastiCache?

2024-06-19 11:14 UTC, javimb commented on relationships/synthesis/APM-APPLICATION-to-INFRA-AWSMQTOPIC.yml
> +      - Distributed Tracing
Is there any reason to not use `APM Metrics`?

2024-06-19 11:14 UTC, javimb commented on relationships/synthesis/APM-APPLICATION-to-INFRA-AWSMQTOPIC.yml
> +relationships:
This line needs to be removed, otherwise what you're doing here is to override the `relationships` section from above.

2024-07-22 09:07 UTC, naxhh commented
Hi @Sanjalee-NewRelic.

We will be closing PR's that haven't had any interaction in a month. If this PR is still needed please reopen the PR and answer the feedback requests.

2024-07-22 09:07 UTC, closed without merging