Add Confluent Cloud Cluster entity
newrelic/entity-definitions pull request #1678
Opened 2024-06-27 10:07 UTC by durgaprasad95

### Relevant information

Creating the **Confluent Cloud Cluster** entity 

### Checklist

* [x] I've read the guidelines and understand the acceptance criteria.
* [ ] The value of the attribute marked as `identifier` will be unique and valid. 
* [x] I've confirmed that my entity type wasn't already defined. If it is I'm providing an explanation above.

2024-06-27 15:39 UTC, javimb requested changes
- Missing [test data](https://github.com/newrelic/entity-definitions?tab=readme-ov-file#testing)
- Missing [dashboard](https://github.com/newrelic/entity-definitions/blob/main/docs/entities/entity_summary.md)
- Missing [summary metrics](https://github.com/newrelic/entity-definitions/blob/main/docs/entities/summary_metrics.md)

2024-06-27 15:39 UTC, javimb commented
By the way, we need the approval of your PM in this PR before merging it.

2024-07-10 09:34 UTC, durgaprasad95 commented
> beep boop bop.
> 
> I have found some errors processing these changes:
> 
> ```
> * Error VALIDATING domainType: 'INFRA-CONFLUENTCLOUDCLUSTER' on synthesis - Exception: No entity matches 'INFRA-CONFLUENTCLOUDCLUSTER' synthesis rules for the given test data: 'MetricRaw.json file - #1' data point. Please review test data and synthesis rules.
> 
> * Error VALIDATING domainType: 'INFRA-CONFLUENTCLOUDCLUSTER' on synthesis - Exception: No entity matches 'INFRA-CONFLUENTCLOUDCLUSTER' synthesis rules for the given test data: 'MetricRaw.json file - #2' data point. Please review test data and synthesis rules.
> ```

@javimb Can you please help me with this? I was not able to figure out what is causing this issue

2024-07-11 13:41 UTC, durgaprasad95 commented
gc rebuild

2024-08-13 14:50 UTC, otaviocarvalho commented
Closing due to inactivity, please feel free to re-open if needed.

2024-08-13 14:50 UTC, closed without merging