feat: changed fb entity definition
newrelic/entity-definitions pull request #1826
Opened 2024-12-18 09:24 UTC by voorepreethi

### Relevant information

### Checklist

* [ ] I've read the guidelines and understand the acceptance criteria.
* [ ] The value of the attribute marked as `identifier` will be unique and valid. 
* [ ] I've confirmed that my entity type wasn't already defined. If it is I'm providing an explanation above.

2024-12-18 12:04 UTC, rohit-bandlamudi-nr requested changes

2024-12-18 12:04 UTC, rohit-bandlamudi-nr commented on entity-types/ext-fluentbit_kuberenetes/definition.yml
> +type: FLUENTBIT_KUBERENETES
can u fix the typo with KUBERNETES

2025-01-06 07:22 UTC, voorepreethi commented
> beep boop bop.
> 
> I have found some errors processing these changes:
> 
> ```
> * Error VALIDATING domainType: 'MEDIA_STREAMING-VIDEO' on Golden metrics for key 'SELECT sum(timeSinceBufferBegin) / sum(timeSinceLastHeartbeat) - filter(sum(timeSincePaused), where actionName = 'CONTENT_RESUME' - filter(sum(timeSinceSeekBegin), where actionName = 'CONTENT_SEEK_END')) * 100 FROM VideoAction WHERE entity.guid IN ('guid') FACET entity.name TIMESERIES' - Exception: The select clause cannot be used to produce a valid golden metric.
> 
> * Error VALIDATING domainType: 'MEDIA_STREAMING-VIDEO' on Golden metrics for key 'SELECT sum(timeSinceAdBufferBegin) / sum(timeSinceLastAdHeartbeat) - filter(sum(timeSinceAdPaused), where actionName = 'AD_RESUME' - filter(sum(timeSinceAdSeekBegin), where actionName = 'AD_SEEK_END')) * 100 FROM VideoAdAction WHERE entity.guid IN ('guid') FACET entity.name TIMESERIES' - Exception: The select clause cannot be used to produce a valid golden metric.
> 
> * Error VALIDATING domainType: 'MEDIA_STREAMING-VIDEO' on Golden metrics for key 'SELECT count(*) WHERE actionName = 'CONENT_ERROR' and contentPlayhead = 0 / (FROM VideoAction SELECT count(*) WHERE actionName = 'CONENT_START' and contentPlayhead=0) * 100 FROM VideoErrorAction WHERE entity.guid IN ('guid') FACET entity.name TIMESERIES' - Exception: Error validating the query.
> 
> * Error VALIDATING domainType: 'MEDIA_STREAMING-VIDEO' on Golden metrics for key 'SELECT count(*) WHERE actionName = 'CONENT_ERROR' and contentPlayhead = 0 / (FROM VideoAction SELECT count(*) WHERE actionName = 'CONENT_START' and contentPlayhead=0) * 100 FROM VideoErrorAction WHERE entity.guid IN ('guid') FACET entity.name TIMESERIES' - analytics.nrql.parser.DiracParserException: Error at line 1 position 17, unexpected 'WHERE'
> 
> * Error VALIDATING domainType: 'MEDIA_STREAMING-VIDEO' on Golden metrics for key 'count(*) WHERE actionName = 'CONENT_ERROR' and contentPlayhead = 0 / (FROM VideoAction SELECT count(*) WHERE actionName = 'CONENT_START' and contentPlayhead=0) * 100' - Exception: The NRQL validator was not able to parse the selection.
> 
> * Error VALIDATING domainType: 'MEDIA_STREAMING-VIDEO' on Golden metrics for key 'SELECT count(*) WHERE actionName = 'AD_ERROR' and adPlayhead = 0 / (FROM VideoAdAction SELECT count(*) WHERE actionName = 'AD_START' and adPlayhead = 0) * 100 FROM VideoErrorAction WHERE entity.guid IN ('guid') FACET entity.name TIMESERIES' - Exception: Error validating the query.
> 
> * Error VALIDATING domainType: 'MEDIA_STREAMING-VIDEO' on Golden metrics for key 'SELECT count(*) WHERE actionName = 'AD_ERROR' and adPlayhead = 0 / (FROM VideoAdAction SELECT count(*) WHERE actionName = 'AD_START' and adPlayhead = 0) * 100 FROM VideoErrorAction WHERE entity.guid IN ('guid') FACET entity.name TIMESERIES' - analytics.nrql.parser.DiracParserException: Error at line 1 position 17, unexpected 'WHERE'
> 
> * Error VALIDATING domainType: 'MEDIA_STREAMING-VIDEO' on Golden metrics for key 'count(*) WHERE actionName = 'AD_ERROR' and adPlayhead = 0 / (FROM VideoAdAction SELECT count(*) WHERE actionName = 'AD_START' and adPlayhead = 0) * 100' - Exception: The NRQL validator was not able to parse the selection.
> 
> * Error VALIDATING domainType: 'MEDIA_STREAMING-VIDEO' on Golden metrics for key 'SELECT count(*) WHERE actionName = 'CONTENT_ERROR' and contentPlayhead > 0 / (FROM VideoAction SELECT count(*) WHERE actionName = 'CONENT_REQUEST') * 100 FROM VideoErrorAction WHERE entity.guid IN ('guid') FACET entity.name TIMESERIES' - Exception: Error validating the query.
> 
> * Error VALIDATING domainType: 'MEDIA_STREAMING-VIDEO' on Golden metrics for key 'SELECT count(*) WHERE actionName = 'CONTENT_ERROR' and contentPlayhead > 0 / (FROM VideoAction SELECT count(*) WHERE actionName = 'CONENT_REQUEST') * 100 FROM VideoErrorAction WHERE entity.guid IN ('guid') FACET entity.name TIMESERIES' - analytics.nrql.parser.DiracParserException: Error at line 1 position 17, unexpected 'WHERE'
> 
> * Error VALIDATING domainType: 'MEDIA_STREAMING-VIDEO' on Golden metrics for key 'count(*) WHERE actionName = 'CONTENT_ERROR' and contentPlayhead > 0 / (FROM VideoAction SELECT count(*) WHERE actionName = 'CONENT_REQUEST') * 100' - Exception: The NRQL validator was not able to parse the selection.
> 
> * Error VALIDATING domainType: 'MEDIA_STREAMING-VIDEO' on Golden metrics for key 'SELECT count(*) WHERE actionName = 'AD_ERROR' and adPlayhead > 0 / (FROM VideoAdAction SELECT count(*) WHERE actionName = 'AD_REQUEST') * 100 FROM VideoErrorAction WHERE entity.guid IN ('guid') FACET entity.name TIMESERIES' - Exception: Error validating the query.
> 
> * Error VALIDATING domainType: 'MEDIA_STREAMING-VIDEO' on Golden metrics for key 'SELECT count(*) WHERE actionName = 'AD_ERROR' and adPlayhead > 0 / (FROM VideoAdAction SELECT count(*) WHERE actionName = 'AD_REQUEST') * 100 FROM VideoErrorAction WHERE entity.guid IN ('guid') FACET entity.name TIMESERIES' - analytics.nrql.parser.DiracParserException: Error at line 1 position 17, unexpected 'WHERE'
> 
> * Error VALIDATING domainType: 'MEDIA_STREAMING-VIDEO' on Golden metrics for key 'count(*) WHERE actionName = 'AD_ERROR' and adPlayhead > 0 / (FROM VideoAdAction SELECT count(*) WHERE actionName = 'AD_REQUEST') * 100' - Exception: The NRQL validator was not able to parse the selection.
> 
> * Error VALIDATING domainType: 'MEDIA_STREAMING-VIDEO' on Summary metrics for key ''averageBitrateMbps': wrong golden metric reference. Couldn't find a golden metric definition with key 'averageBitrateMbps', please populate 'goldenMetric' with a valid reference to an existing golden metric.' - Exception: 'averageBitrateMbps': wrong golden metric reference. Couldn't find a golden metric definition with key 'averageBitrateMbps', please populate 'goldenMetric' with a valid reference to an existing golden metric.
> 
> * Error VALIDATING domainType: 'MEDIA_STREAMING-VIDEO' on Summary metrics for key ''adAverageBitrateMbps': wrong golden metric reference. Couldn't find a golden metric definition with key 'adAverageBitrateMbps', please populate 'goldenMetric' with a valid reference to an existing golden metric.' - Exception: 'adAverageBitrateMbps': wrong golden metric reference. Couldn't find a golden metric definition with key 'adAverageBitrateMbps', please populate 'goldenMetric' with a valid reference to an existing golden metric.
> ```

These are not from my changes

2025-01-08 11:20 UTC, vlopeziglesias approved these changes

2025-01-08 11:20 UTC, merged