Add ext-oracle definition to entity definitions
newrelic/entity-definitions pull request #506
Opened 2022-03-29 03:05 UTC by edyu002

### Relevant information

Add ext-oracle entity type as part of the SAP entities definitions. This was proposed with the first batch of SAP entities, but not put in as we didn't have Oracle data collected then. Now we have worked out to collect metrics for ORACLE based on  customer request, it's time to add it.

### Checklist

* [x ] I've read the guidelines and understand the acceptance criteria.
* [ x] The value of the attribute marked as `identifier` will be unique and valid. 
* [ x] I've confirmed that my entity type wasn't already defined. If it is I'm providing an
 explanation above.

2022-03-29 06:23 UTC, danipl approved these changes

2022-03-29 07:38 UTC, naxhh requested changes
Blocking this for a bit of discussion about oracle entity types

2022-03-29 08:42 UTC, naxhh approved these changes
LGTM

@edyu002 we have an existing oracle definition
https://github.com/newrelic/entity-definitions/tree/main/definitions/infra-oracledbinstance

I would suggest you to check if that fits with your use case to avoid a new type.

If that's not the case lets us know and we will merge this one

2022-03-29 15:07 UTC, edyu002 commented
> LGTM
> 
> @edyu002 we have an existing oracle definition https://github.com/newrelic/entity-definitions/tree/main/definitions/infra-oracledbinstance
> 
> I would suggest you to check if that fits with your use case to avoid a new type.
> 
> If that's not the case lets us know and we will merge this one

We'd like this request get merged first.

We have looked at the infra-oracledbinstance definition in the process. There are 2 issues for us to use it: 1. As the data sources are different, metrics measured are not the same. 2. For infra domain types, we can not define entity detail UI based on data source. So we won't be able to see Oracle data in entity UI detail screen. 
We are trying to re-use infra-host by simulating OTel metrics, which is simpler, but still waiting infra team to finish their support for open-telemetry to show the UI. In addition, a recent entity definition change on infra-host has broken our simulation . Our first customer installation is coming at 4/8 and they are using Oracle, we have to get Oracle support in before that. 
To use infra-oracle may require some in-depth discussions and coordinations, and may impact architecture of the infra entities. For the long term, we will be happy to work with all the involved teams to explore the possibility of merging the entities.

2022-03-29 15:12 UTC, edyu002 commented
> LGTM
> 
> @edyu002 we have an existing oracle definition https://github.com/newrelic/entity-definitions/tree/main/definitions/infra-oracledbinstance
> 
> I would suggest you to check if that fits with your use case to avoid a new type.
> 
> If that's not the case lets us know and we will merge this one

We found it's not feasible to use infra-oracledbinstance for now. We'd like to get this pull request merged.

2022-03-30 08:08 UTC, otaviocarvalho approved these changes

2022-03-30 08:18 UTC, merged